### ISSUE TITLE
All Adaptors have Confusing Error Message when they need "localhost"

### ISSUE THREAD

**Issue by melrom** [radical-cybertools/saga-python#283]
This is partly a documentation issue, but my main issue with the code is a super confusing error message when an explicit hostname is given instead of localhost for a non-ssh adaptor.

For instance, my URL can be "slurm+ssh://stampede.tacc.utexas.edu", but when I use "slurm://stampede.tacc.utexas.edu", I get:

<pre><code>
AN ERROR OCCURRED: expect local host for 'fork://', not 'stampede.tacc.utexas.edu' (/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/utils/pty_shell_factory.py +509 (_create_master_entry)  :  "expect local host for '%s://', not '%s'" % (url.schema, url.host)))
Traceback (most recent call last):
  File "two_exec_test.py", line 64, in main
    pilotjob = pilot_compute_service.create_pilot(pilot_description)
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/BigJob-0.50-py2.6.egg/pilot/impl/pilotcompute_manager.py", line 78, in create_pilot
    bj = self.__start_bigjob(bj_dict)
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/BigJob-0.50-py2.6.egg/pilot/impl/pilotcompute_manager.py", line 185, in __start_bigjob
    pilot_compute_description = bj_dict["pilot_compute_description"]
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/BigJob-0.50-py2.6.egg/bigjob/bigjob_manager.py", line 215, in start_pilot_job
    self.js = self._ocache.get_obj (lrms_saga_url, lambda : SAGAJobService (lrms_saga_url))
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/utils/object_cache.py", line 47, in get_obj
    obj = creator ()
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/BigJob-0.50-py2.6.egg/bigjob/bigjob_manager.py", line 215, in <lambda>
    self.js = self._ocache.get_obj (lrms_saga_url, lambda : SAGAJobService (lrms_saga_url))
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/utils/signatures.py", line 453, in takes_invocation_proxy
    return method(*pargs, **pkwargs)
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/utils/signatures.py", line 484, in returns_invocation_proxy
    result = method (*args, **kwargs)
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/job/service.py", line 108, in __init__
    url, session, ttype=_ttype)
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/utils/signatures.py", line 453, in takes_invocation_proxy
    return method(*pargs, **pkwargs)
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/utils/signatures.py", line 484, in returns_invocation_proxy
    result = method (*args, **kwargs)
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/base.py", line 96, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/adaptors/cpi/decorators.py", line 51, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/adaptors/slurm/slurm_job.py", line 288, in init_instance
    self._open ()
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/adaptors/slurm/slurm_job.py", line 359, in _open
    self._logger)
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/utils/pty_shell.py", line 205, in __init__
    self.pty_info   = self.factory.initialize (url, session, self.logger)
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/utils/pty_shell_factory.py", line 153, in initialize
    info = self._create_master_entry (url, session, logger)
  File "/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/utils/pty_shell_factory.py", line 509, in _create_master_entry
    "expect local host for '%s://', not '%s'" % (url.schema, url.host))
BadParameter: expect local host for 'fork://', not 'stampede.tacc.utexas.edu' (/home1/01871/melrom/.bigjob/python/lib/python2.6/site-packages/saga_python-0.9.12-py2.6.egg/saga/utils/pty_shell_factory.py +509 (_create_master_entry)  :  "expect local host for '%s://', not '%s'" % (url.schema, url.host)))
</code></pre>

As a user, I am not sure what to make of this. I didn't do anything at all with the fork adaptor. Why does it think I am using fork? So, maybe you can't use slurm://stampede.tacc.utexas.edu, and I just didn't know that (although admittedly, I thought this would fly when I'm on the target host). "slurm://localhost" appears to work just fine, but "slurm://login1.stampede.tacc.utexas.edu" yields the same issue. I later found out this is the expected behavior, but if I were an end-user, I think I would be quite confused.

When tested with PBS adaptor, I got the same issue. Had to explicitly say pbs+ssh:// or pbs://localhost. The error was also "fork:// expects localhost." 

I installed bliss to see what the expected behavior has been in the past. It turns out, it was always this way (that you had to use pbs://localhost, slurm://localhost, etc), but the bliss error is much more intuitive:

"An error occured during job execution: SAGA Exception (NoSuccess): [saga.plugin.job.pbssh] Can't use india.futuregrid.org as a (non-local) hostname in conjunction with pbs://. Try pbs+ssh:// instead (No Stacktrace)"

**Comment by andre-merzky** [comment]
This has been addressed in the various batch adaptors over time.  Please  reopen if that still pops up!
