### ISSUE TITLE
AttributeError: 'BadParameter' object has no attribute 'traceback'

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/saga-python#504]
While reviewing some of the PRs I get this from localjob.py.

```
2016-01-18 16:05:12,932: radical.saga        : MainProcess                     : MainThread     : ERROR   : BadParameter: 'JobDescription.FileTransfer' (['/tmp/myinput > /tmp/copiedinput']) is not supported by adaptor saga.adaptor.shell_job
An exception occured: 'JobDescription.FileTransfer' (['/tmp/myinput > /tmp/copiedinput']) is not supported by adaptor saga.adaptor.shell_job (/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/saga/job/service.py +300 (create_job)  :  raise se.BadParameter._log (self._logger, msg)) 
Traceback (most recent call last):
  File "localjob.py", line 87, in <module>
    sys.exit (main())
  File "localjob.py", line 83, in main
    print " \n*** Backtrace:\n %s" % ex.traceback
AttributeError: 'BadParameter' object has no attribute 'traceback'
```

The "not supported" is intentional, my question is about the traceback. Is that an error in the example script or is that supposed to work?

**Comment by andre-merzky** [comment]
Hmm, I am not exactly sure what happened (and am too lazy to dig around), but I could have sworn that we had that property in the past.  That is used in almost all examples after all!  Anyway, I'll open a PR to (re-)introduce it.  Thanks!

**Comment by marksantcroos** [comment]
Seems to do the job. Thanks!
