### ISSUE TITLE
Error with amazon_ec2: Connection Timeout Error

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/saga-python#526]
I am trying to run the [amazon_ec2](https://github.com/radical-cybertools/saga-python/blob/devel/examples/resource/amazon_ec2.py) script, but I find that I am getting a Connection Timeout Error when running the code. Instantiating the VM is not a problem. Rather, the error occurs when I try to create a service which submits a job to the VM.

I am using the most current version of SAGA. Please find below the error message.

```
2016-03-23 22:44:16,730: radical.saga.cpi    : MainProcess                     : MainThread     : ERROR   : read from process failed '[Errno 5] Input/output error' : (ssh: connect to host 52.90.55.203 port 22: Connection timed out
) ((ssh: connect to host 52.90.55.203 port 22: Connection timed out
)) (/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +43 (translate_exception)  :  e = se.BadParameter (cmsg))
Traceback (most recent call last):
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 305, in _initialize_pty
    n, match = pty_shell.find (prompt_patterns, delay)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_process.py", line 790, in find
    raise ptye.translate_exception (e, "(%s)" % data)
BadParameter: read from process failed '[Errno 5] Input/output error' : (ssh: connect to host 52.90.55.203 port 22: Connection timed out
) ((ssh: connect to host 52.90.55.203 port 22: Connection timed out
)) (/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +43 (translate_exception)  :  e = se.BadParameter (cmsg))
An exception occured: (BadParameter) read from process failed '[Errno 5] Input/output error' : (ssh: connect to host 52.90.55.203 port 22: Connection timed out
) ((ssh: connect to host 52.90.55.203 port 22: Connection timed out
)) (/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +43 (translate_exception)  :  e = se.BadParameter (cmsg)) 
Traceback (most recent call last):
  File "amazon_ec2.py", line 160, in <module>
    sys.exit(main())
  File "amazon_ec2.py", line 118, in main
    js = saga.job.Service(cr.access, session=session)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/job/service.py", line 115, in __init__
    url, session, ttype=_ttype)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py", line 504, in init_instance
    self._logger, opts=self.opts)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 244, in __init__
    posix=self.posix)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 196, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 411, in _initialize_pty
    raise ptye.translate_exception (e)
saga.exceptions.BadParameter: read from process failed '[Errno 5] Input/output error' : (ssh: connect to host 52.90.55.203 port 22: Connection timed out
) ((ssh: connect to host 52.90.55.203 port 22: Connection timed out
)) (/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +43 (translate_exception)  :  e = se.BadParameter (cmsg))
```

**Comment by andre-merzky** [comment]
Hi Ming, 

does the error persist when you connect, say, 10 min later?  Also, please run  with `RADICAL_SAGA_PTY_VERBOSE=DEBUG` set, and search for the executed ssh command line in the output.  Does that use the correct key and username?  Does that command line work for you outside of SAGA?

Thanks, Andre.

**Comment by mingtaiha** [comment]
Hey Andre,

The same error does persist when I connect 10 min later. It should be noted that I get this problem for both .pem and id_rsa.pub keys. After our call, I ran into this error but have been trying to troubleshoot this on my own.

I've managed to fix this error (yay), but a new error arose (boo), for which I will open a new ticket.

It turns out that you need to add a rule in your security group to your inbound traffic to enable SSH traffic so the EC2 compute node can know to listen to the SSH port. A more detailed description is included [here](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html). This is a point we should mention in our docs, at least for the EC2 part of the SAGA tutorial.

**Comment by vivek-bala** [comment]
This issue is resolved. Thanks for the detailed description Ming!
