### ISSUE TITLE
Could not detect shell prompt (timeout)

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/saga-python#527]
I am trying to run the [amazon_ec2](https://github.com/radical-cybertools/saga-python/blob/devel/examples/resource/amazon_ec2.py) script (again!), but I get an error indicating that SAGA cannot detect a shell prompt. I have waited 10mins before defining a service which uses the instance, so the VM should have had enough time to setup.

Below is the some SAGA debug messages and the error message. I ran the script using EC2 both the .pem and id_rsa keys, and both led to the same error.

```
2016-03-24 11:40:57,609: radical.saga.cpi    : MainProcess                     : MainThread     : INFO    : got hostkey prompt
2016-03-24 11:40:57,609: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [    4] (yes\n)
2016-03-24 11:40:57,612: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : read : [    4] [   82] (\nWarning: Permanently added '54.210.228.94' (ECDSA) to the list of known hosts.\n)
2016-03-24 11:40:58,614: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   51] ( export PS1='$' > /dev/null 2>&1 || set prompt='$'\n)
2016-03-24 11:40:58,614: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   28] ( printf 'HELLO_%d_SAGA\n' 1\n)
2016-03-24 11:40:59,615: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   51] ( export PS1='$' > /dev/null 2>&1 || set prompt='$'\n)
2016-03-24 11:40:59,615: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   28] ( printf 'HELLO_%d_SAGA\n' 2\n)
2016-03-24 11:41:00,616: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   51] ( export PS1='$' > /dev/null 2>&1 || set prompt='$'\n)
2016-03-24 11:41:00,616: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   28] ( printf 'HELLO_%d_SAGA\n' 3\n)
2016-03-24 11:41:01,626: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   51] ( export PS1='$' > /dev/null 2>&1 || set prompt='$'\n)
2016-03-24 11:41:01,626: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   28] ( printf 'HELLO_%d_SAGA\n' 4\n)
2016-03-24 11:41:02,628: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   51] ( export PS1='$' > /dev/null 2>&1 || set prompt='$'\n)
2016-03-24 11:41:02,628: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   28] ( printf 'HELLO_%d_SAGA\n' 5\n)
2016-03-24 11:41:03,631: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   51] ( export PS1='$' > /dev/null 2>&1 || set prompt='$'\n)
2016-03-24 11:41:03,631: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   28] ( printf 'HELLO_%d_SAGA\n' 6\n)
2016-03-24 11:41:04,641: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   51] ( export PS1='$' > /dev/null 2>&1 || set prompt='$'\n)
2016-03-24 11:41:04,642: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   28] ( printf 'HELLO_%d_SAGA\n' 7\n)
2016-03-24 11:41:05,651: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   51] ( export PS1='$' > /dev/null 2>&1 || set prompt='$'\n)
2016-03-24 11:41:05,651: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   28] ( printf 'HELLO_%d_SAGA\n' 8\n)
2016-03-24 11:41:06,661: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   51] ( export PS1='$' > /dev/null 2>&1 || set prompt='$'\n)
2016-03-24 11:41:06,662: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   28] ( printf 'HELLO_%d_SAGA\n' 9\n)

2016-03-24 11:41:07,663: radical.saga.cpi    : MainProcess                     : MainThread     : ERROR   : Could not detect shell prompt (timeout) (/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
Traceback (most recent call last):
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 288, in _initialize_pty
    raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout) (/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
2016-03-24 11:41:07,663: radical.saga.pty    : MainProcess                     : MainThread     : DEBUG   : Traceback (most recent call last):
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 288, in _initialize_pty
    raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout) (/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))

An exception occured: (NoSuccess) Could not detect shell prompt (timeout) (/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)")) 
Traceback (most recent call last):
  File "amazon_ec2.py", line 160, in <module>
    sys.exit(main())
  File "amazon_ec2.py", line 118, in main
    js = saga.job.Service(cr.access, session=session)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/job/service.py", line 115, in __init__
    url, session, ttype=_ttype)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py", line 504, in init_instance
    self._logger, opts=self.opts)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 244, in __init__
    posix=self.posix)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 196, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 411, in _initialize_pty
    raise ptye.translate_exception (e)
saga.exceptions.NoSuccess: Could not detect shell prompt (timeout) (/home/mingtaiha/ve/ve.testing_philip_fowler/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
```

**Comment by mingtaiha** [comment]
I am trying to submit a test job to prepare for an AIMES experiment on Stampede, but I get the following error. I am using the most current version of RP and SAGA in order to run the job. The error that I am getting seems very reminiscent of the one I got on EC2, and thus has been grouped together.

```
2016-03-30 08:13:41,320: radical.saga.pty    : MainProcess                     : MainThread     : ERROR   : Could not detect shell prompt (timeout) (/home/mingtha/ve/aimes-swift-experiments/local/lib/python
2.7/site-packages/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
Traceback (most recent call last):
  File "/home/mingtha/ve/aimes-swift-experiments/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 288, in _initialize_pty
    raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout) (/home/mingtha/ve/aimes-swift-experiments/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess (
"Could not detect shell prompt (timeout)"))
2016-03-30 08:13:41,320: radical.saga.pty    : MainProcess                     : MainThread     : DEBUG   : Traceback (most recent call last):
  File "/home/mingtha/ve/aimes-swift-experiments/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 288, in _initialize_pty
    raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout) (/home/mingtha/ve/aimes-swift-experiments/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess (
"Could not detect shell prompt (timeout)"))

Caught exception: Could not detect shell prompt (timeout) (/home/mingtha/ve/aimes-swift-experiments/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSu
ccess ("Could not detect shell prompt (timeout)"))
Traceback (most recent call last):
  File "/home/mingtha/ve/aimes-swift-experiments/local/lib/python2.7/site-packages/aimes/emgr/emgr.py", line 577, in execute_workload
    run['pilots']    = pmgr.submit_pilots(run['pdescs'])
  File "/home/mingtha/ve/aimes-swift-experiments/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 361, in submit_pilots
    resource_config=resource_cfg)
  File "/home/mingtha/ve/aimes-swift-experiments/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 433, in register_start_pilot_request
    shell = sup.PTYShell(url, self._session)
  File "/home/mingtha/ve/aimes-swift-experiments/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 244, in __init__
    posix=self.posix)
  File "/home/mingtha/ve/aimes-swift-experiments/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 196, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/mingtha/ve/aimes-swift-experiments/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 411, in _initialize_pty
    raise ptye.translate_exception (e)
NoSuccess: Could not detect shell prompt (timeout) (/home/mingtha/ve/aimes-swift-experiments/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +288 (_initialize_pty)  :  raise se.NoSuccess (
"Could not detect shell prompt (timeout)"))
```

**Comment by andre-merzky** [comment]
Hey Ming - very reminiscent indeed -- but you'll learn to hate the error message sooner or later, because it can have all kinds of causes.. ;)  It really mostly tells you that the ssh connection could not be established, be it due to network errors, misconfigurations in RP, key mismatch, or resource exhaustion...

What was the specific application you used?  Is the error reproducible?  Could you login to stampede at that time?

You may want to rerun with `RADICAL_SAGA_PTY_VERBOSE=DEBUG`, and look for the executed ssh command -- does that command  work when used directly on the command line?

Best, Andre.

**Comment by mingtaiha** [comment]
Bleh, this is the stuff I don't like. Luckily, I am not getting an error on Stampede right now. I will have to test it on EC2 when I get the chance.

**Comment by mingtaiha** [comment]
Is there a way to (relatively) quickly decide whether this problem is an error on the SAGA side or on the Remote Machine side?

**Comment by andre-merzky** [comment]
> Is there a way to (relatively) quickly decide whether this problem is an error on the SAGA side or on the Remote Machine side?

No, not really.  Essentially we see an ssh connection not coming up.  Alas, ssh is rather silent about its failure modes, so we usually have to solve that out of band....

**Comment by andre-merzky** [comment]
Hey Ming - is this still a problem?

**Comment by dmanubens** [comment]
I have seen also this error message in my case. I wonder if wouldn't it be related to the problem of concurrent  ssh channels I reported here #533 .

**Comment by marksantcroos** [comment]
When you encounter this, and you suspect it is because of a slow login node, or bad network, try setting:
```
export SAGA_PTY_SSH_TIMEOUT=N
```
Where N is something like `60` or `120`, depending on the degree of slowness.

**Comment by dmanubens** [comment]
By now I have been able to overcome timeout(s), setting `export SAGA_PTY_SSH_TIMEOUT=60`
Thanks a lot @marksantcroos !

**Comment by dmanubens** [comment]
Hi again,
I am not sure about my last comment. Now at BSC we are around 8 users of Autosubmit (https://pypi.python.org/pypi/autosubmit). We have been experiencing timout(s) randomly even though setting the timout env. variable to  `60` or `120`. It happens indistinctly while trying to connect to local resource (fork), slurm and lsf. It could be network issue but it would be quite surprising that 120 is not enough. At the moment of having issue, I have no problem opening an interactive session.

**Comment by dmanubens** [comment]
Hi, now I blame again the network. Some of our users didn't really set the timout env. variable correctly! Today it's behaving better with `120`. Just one issue that I don't know if could be resolved similarly:
```
2016-05-05 20:59:25,091: radical.saga.cpi : MainProcess : MainThread : ERROR : IncorrectState: Lost shell connection to mn-pr1eaq00 2016-05-05 20:59:25,091: radical.utils : MainProcess : MainThread : ERROR : Could not create lease object Traceback (most recent call last): File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/radical.utils-0.40-py2.7.egg/radical/utils/lease_manager.py", line 175, in create_object obj = LeaseObject (self, self._log, creator, args) File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/radical.utils-0.40-py2.7.egg/radical/utils/leasemanager.py", line 33, in __init_ self.obj = creator (*args) File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/shell/shell_file.py", line 274, in shell_creator return sups.PTYShell (url, self.get_session(), self.logger) File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/sagapython-0.40-py2.7.egg/saga/utils/pty_shell.py", line 243, in __init_ posix=self.posix) File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell_factory.py", line 209, in initialize "Lost shell connection to %s" % info['host_str'])
```

**Comment by dmanubens** [comment]
The `Lost shell connection` error is raising sometimes randomly when using `SAGA_PTY_SSH_TIMEOUT=120` Does this have something to do? or shall I open a new ticket ?

**Comment by ibethune** [comment]
Closed, the timeout issue is resolved.  #533 remains open.
