### ISSUE TITLE
SAGA hangs upon job exit on OSG

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/saga-python#577]
I tried submitting a job to OSG managed to run /bin/sleep using the feature/osg_optimization_run_job branch, but encounter an error when the job ends. When checking the queue on OSG, I find that the job terminates correctly. Here is the output of the corresponding saga-condor-job-<job_id>.log

```
[0] 02:42:18 UTC [mha@xd-login:~]$ cat saga-condor-job-6473754_0.log 
000 (6473754.000.000) 07/25 02:28:59 Job submitted from host: <129.79.53.198:9615?addrs=129.79.53.198-9615&noUDP&sock=41317_5069>
...
001 (6473754.000.000) 07/25 02:30:38 Job executing on host: <10.1.2.40:28303?CCBID=129.79.53.179:9784%3faddrs%3d129.79.53.179-9784#1365380&addrs=10.1.2.40-28303&noUDP>
...
006 (6473754.000.000) 07/25 02:30:46 Image size of job updated: 27
    4  -  MemoryUsage of job (MB)
    3448  -  ResidentSetSize of job (KB)
...
006 (6473754.000.000) 07/25 02:31:38 Image size of job updated: 4136
    4  -  MemoryUsage of job (MB)
    3448  -  ResidentSetSize of job (KB)
...
005 (6473754.000.000) 07/25 02:31:38 Job terminated.
    (1) Normal termination (return value 0)
        Usr 0 00:00:00, Sys 0 00:00:00  -  Run Remote Usage
        Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
        Usr 0 00:00:00, Sys 0 00:00:00  -  Total Remote Usage
        Usr 0 00:00:00, Sys 0 00:00:00  -  Total Local Usage
    0  -  Run Bytes Sent By Job
    26368  -  Run Bytes Received By Job
    0  -  Total Bytes Sent By Job
    26368  -  Total Bytes Received By Job
    Partitionable Resources :    Usage  Request Allocated
       Cpus                 :                 1         1
       Disk (KB)            :       44       27 190410144
       Memory (MB)          :        4     1800      1920
...
```

On the client side, however, I get the following error:

```
2016-07-25 04:34:35,113: radical.saga.cpi    : MainProcess                     : MainThread     : INFO    : Got ret: 1       out: 
2016-07-25 04:34:35,113: radical.saga.cpi    : MainProcess                     : MainThread     : ERROR   : Error getting job history via 'condor_history': 
Traceback (most recent call last):
  File "saga_test_slurm.py", line 23, in <module>
    myjob.wait()
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/job/job.py", line 589, in wait
    return self._adaptor.wait (timeout, ttype=ttype)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/adaptors/condor/condorjob.py", line 1579, in wait
    self.js._job_wait(self._id, timeout)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/adaptors/condor/condorjob.py", line 1225, in _job_wait
    state = self._job_get_state(job_id=job_id)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/adaptors/condor/condorjob.py", line 1122, in _job_get_state
    self._job_get_info(job_id=job_id)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/adaptors/condor/condorjob.py", line 855, in _job_get_info
    log_error_and_raise(message, saga.NoSuccess, self._logger)
  File "/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/adaptors/condor/condorjob.py", line 33, in log_error_and_raise
    raise exception(message)
saga.exceptions.NoSuccess: Error getting job history via 'condor_history':  (/home/mingtha/ve/ve.aimes_experience/local/lib/python2.7/site-packages/saga/adaptors/condor/condorjob.py +33 (log_error_and_raise)  :  raise exception(message))
```

Upon investigation, I find that the return value is 1, i.e. `ret = 1`. I am assuming that the return value of a successful execution is 0, and that any other value denotes an unsuccessful execution for most machines. Is this the case for OSG as well?

Here is the file with messages from `RADICAL_SAGA_VERBOSE=DEBUG`, `RADICAL_SAGA_PTY_VERBOSE=DEBUG`

**Comment by andre-merzky** [comment]
You forgot to attach/link the client log.  Also, are there any log files in the pilot sandbox?

**Comment by mingtaiha** [comment]
I did forget the client log, so here it is. I didn't get any log files from the pilot sandbox since I only used SAGA. 
[osg_exit_hangup.txt](https://github.com/radical-cybertools/saga-python/files/381819/osg_exit_hangup.txt)

**Comment by andre-merzky** [comment]
Please give `feature/osg_optimizations` another try!

**Comment by andre-merzky** [comment]
Considered solved.
