### ISSUE TITLE
Condor adaptor: Unpacking error

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/saga-python#598]
```
$ radical-utils-version 
v0.41.1-39-gf1537da@experiment-aimes
$ sagapython-version 
v0.41-71-g1398b25@experiment-aimes
```
I see the following (non-fatal for the session) error printed to STDERR when running a RP session on XSEDE OSG Virtual Cluster:
```
/Traceback (most recent call last):
  File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/radical/utils/threads.py", line 154, in run
    self._result    = self._call(*self._args, **self._kwargs)
  File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/saga/adaptors/condor/condorjob.py", line 1503, in container_get_states
    bulk_info = self._job_get_info_bulk(cluster_id, job_ids)
  File "/home/mturilli/ve/AIMES-EXPERIENCE/local/lib/python2.7/site-packages/saga/adaptors/condor/condorjob.py", line 978, in _job_get_info_bulk
    = [col.strip() for col in row.split(',')]
ValueError: need more than 1 value to unpack
```
Session ID: `rp.session.radical.mturilli.017148.0000`

**Comment by mturilli** [comment]
Got this two more time: Session `rp.session.radical.mturilli.017156.0000` and `rp.session.radical.mturilli.017155.0000`. 

I will have to stop this specific experiment and try with different runs while waiting to see whether it can be fixed.

**Comment by mturilli** [comment]
This seems to be affecting all runs now, irrespective of pilot/CU numbers.

**Comment by andre-merzky** [comment]
Christmas break interfered, but a patch (a1d786ac) has been pushed to make the parsing of the `condor_history`  output more resilient against errors in the condor backend.

**Comment by andre-merzky** [comment]
This is confirmed fixed.
