### ISSUE TITLE
Get saga running on Cheyenne

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/saga-python#657]
I am trying to get saga working on Cheyenne which PBSPro 14.2. I made the following edits in the feature/cheyenne branch: https://github.com/radical-cybertools/saga-python/commit/6905568d5afa339f7da575cb1f6875c9679498af.

I run a [test script](https://github.com/radical-cybertools/saga-python/blob/feature/cheyenne/tests/test_cheyenne.py) and I get the following error:

```
(test-saga) vivekb@cheyenne5:~/repos/saga-python/examples/jobs> python test_cheyenne_pbspro.py 
Job ID      : None
Job State   : New

...starting job...

Callback    : job state changed to 'Pending'

Job ID      : [pbspro://localhost/]-[4474132]

Listing active jobs: 
 * [pbspro://localhost/]-[4474132]

...waiting for job...

2018-02-12 13:05:22,622: radical.saga.cpi    : MainProcess                     : Thread-1       : ERROR   : Error retrieving job info via 'qstat': qstat: conflicting options.
usage: 
qstat [-f] [-J] [-p] [-t] [-x] [-E] [ job_identifier... | destination... ]
qstat [-a|-i|-r|-H|-T] [-J] [-t] [-u user] [-n] [-s] [-G|-M] [-1] [-w]
	[ job_identifier... | destination... ]
qstat -Q [-f] [ destination... ]
qstat -q [-G|-M] [ destination... ]
qstat -B [-f] [ server_name... ]
qstat --version

Traceback (most recent call last):
  File "/glade/u/home/vivekb/ves/test-saga/lib/python2.7/site-packages/saga/adaptors/pbspro/pbsprojob.py", line 76, in run
    new_job_info = self.js._job_get_info(job_id, reconnect=False)
  File "/glade/u/home/vivekb/ves/test-saga/lib/python2.7/site-packages/saga/adaptors/pbspro/pbsprojob.py", line 866, in _job_get_info
    log_error_and_raise(message, saga.NoSuccess, self._logger)
  File "/glade/u/home/vivekb/ves/test-saga/lib/python2.7/site-packages/saga/adaptors/pbspro/pbsprojob.py", line 115, in log_error_and_raise
    raise exception(message)
NoSuccess: Error retrieving job info via 'qstat': qstat: conflicting options.
usage: 
qstat [-f] [-J] [-p] [-t] [-x] [-E] [ job_identifier... | destination... ]
qstat [-a|-i|-r|-H|-T] [-J] [-t] [-u user] [-n] [-s] [-G|-M] [-1] [-w]
	[ job_identifier... | destination... ]
qstat -Q [-f] [ destination... ]
qstat -q [-G|-M] [ destination... ]
qstat -B [-f] [ server_name... ]
qstat --version
 (/glade/u/home/vivekb/ves/test-saga/lib/python2.7/site-packages/saga/adaptors/pbspro/pbsprojob.py +115 (log_error_and_raise)  :  raise exception(message))
^CTraceback (most recent call last):
  File "test_cheyenne_pbspro.py", line 108, in <module>
    sys.exit(main())
  File "test_cheyenne_pbspro.py", line 87, in main
    job.wait()
  File "/glade/u/home/vivekb/ves/test-saga/lib/python2.7/site-packages/saga/job/job.py", line 588, in wait
    return self._adaptor.wait (timeout, ttype=ttype)
  File "/glade/u/home/vivekb/ves/test-saga/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/glade/u/home/vivekb/ves/test-saga/lib/python2.7/site-packages/saga/adaptors/pbspro/pbsprojob.py", line 1204, in wait
    self.js._job_wait(job_id=self._id, timeout=timeout)
  File "/glade/u/home/vivekb/ves/test-saga/lib/python2.7/site-packages/saga/adaptors/pbspro/pbsprojob.py", line 1025, in _job_wait
    time.sleep(SYNC_WAIT_UPDATE_INTERVAL)
KeyboardInterrupt
```

Not sure how to proceed. Let me know if I can help debug.

**Comment by mturilli** [comment]
This is the pleasure of slightly varying argument options across versions. Can you increase SAGA verbosity and see the whole `qstat` command as issued by SAGA?

**Comment by vivek-bala** [comment]
Thanks Matteo! I missed one of the arguments. This is resolved now.

**Comment by vivek-bala** [comment]
Actually, I'll leave it open and PR to Andre.

**Comment by andre-merzky** [comment]
PR looks good to me - approved.  We recently discussed that we may want to do hotfix releases for issues like this.  If you think that's warranted, please redirect the PR to master, and I'll take care of pushing it out - otherwise feel free to merge into devel.
