### ISSUE TITLE
Installing within a conda environment: "setproctitle.so: undefined symbol: _intel_fast_memset"

### ISSUE THREAD

**Issue by brainstorm** [radical-cybertools/saga-python#665]
I slightly modified `examples/pbsprojob.py` to match our HPC setup, but after `pip install -e .`-ing `saga-python` I'm getting this:

```
$ python pbsraijin.py
Traceback (most recent call last):
  File "pbsraijin.py", line 15, in <module>
    import saga
  File "/home/005/rg3930/dev/saga-python/src/saga/__init__.py", line 8, in <module>
    import radical.utils        as ru
  File "/g/data/gx8/tmp/miniconda_roman/lib/python2.7/site-packages/radical/utils/__init__.py", line 13, in <module>
    from .process        import Process
  File "/g/data/gx8/tmp/miniconda_roman/lib/python2.7/site-packages/radical/utils/process.py", line 13, in <module>
    import setproctitle    as spt
ImportError: /g/data/gx8/tmp/miniconda_roman/lib/python2.7/site-packages/setproctitle.so: undefined symbol: _intel_fast_memset
```

Along several undefined symbols:

```
bash-4.1$ nm /g/data/gx8/tmp/miniconda_roman/lib/python2.7/site-packages/setproctitle.so | grep U
                 U PyArg_ParseTupleAndKeywords
                 U PyDict_SetItemString
                 U PyErr_Clear
                 U PyErr_NoMemory
                 U PyErr_Occurred
                 U PyFile_FromString
                 U PyImport_ImportModule
                 U PyInt_AsLong
                 U PyModule_GetDict
                 U PyObject_CallMethod
                 U PyString_AsString
                 U PyString_Size
                 U Py_BuildValue
                 U Py_GetArgcArgv
                 U Py_InitModule4_64
                 U _Py_NoneStruct
                 U __environ@@GLIBC_2.2.5
                 U __intel_sse2_strdup
                 U __intel_sse2_strlen
                 U _intel_fast_memset
                 U environ@@GLIBC_2.2.5
                 U fputs@@GLIBC_2.2.5
                 U free@@GLIBC_2.2.5
                 U getenv@@GLIBC_2.2.5
                 U malloc@@GLIBC_2.2.5
                 U prctl@@GLIBC_2.2.5
                 U snprintf@@GLIBC_2.2.5
                 U stderr@@GLIBC_2.2.5
                 U vfprintf@@GLIBC_2.2.5
```

I'm running on:

```
bash-4.1$ cat /etc/issue.net
CentOS release 6.9 (Final)
Kernel \r on an \m

bash-4.1$ uname -a
Linux raijin5 3.10.0-693.17.1.el6.x86_64 #1 SMP Fri Feb 9 03:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Maybe having it under [conda-forge](https://conda-forge.org/#add_recipe) would solve this issue though.

**Comment by iparask** [comment]
Hello @brainstorm. As far as I know SAGA install correctly to a conda environment. Can you do `radical-stack` and include the version on this ticket?

Also, can you try updating setproctitle from a conda channel and see if you get the same error when you try to import it? 

If it is a dependency issue, having it under `conda-forge` may solve this issue.

**Comment by iparask** [comment]
Hello @brainstorm, `saga-python` is under the `conda-forge` channel now. If you are still interested in using `saga-python` I suggest you install it from the `conda-forge` channel.

Please keep in mind that this channel support just started and unforeseen issues may arise. We welcome any issue that you may find!

Thank you!

**Comment by lee212** [comment]
fixed
