### ISSUE TITLE
RepEx/EnTK job fails with "WARNING : Previously running job has disappeared"

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/saga-python#668]
Issue seems to be originating from the saga layer. This is the error I see on the terminal:

```2018-05-02 03:45:06,060: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Received heartbeat response
2018-05-02 03:45:06,061: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
2018-05-02 03:45:06,061: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Received heartbeat request
2018-05-02 03:45:06,061: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Sent heartbeat response
2018-05-02 03:45:08,395: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : WARNING : Previously running job has disappeared. This probably means that the backend doesn't store information about finished jobs. Setting state to 'DONE'.
2018-05-02 03:45:08,395: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : INFO    : Job monitoring thread updating Job [torque+gsissh://supermic.cct-lsu.xsede.org:2222/]-[411864] (old state: Running, new state: Do
ne)
2018-05-02 03:45:10,317: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating WFprocessor
2018-05-02 03:45:10,317: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: DONE
2018-05-02 03:45:10,317: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has completed
2018-05-02 03:45:10,318: radical.entk.wfprocessor.0001: wfprocessor                     : MainThread     : INFO    : Terminating enqueue-thread
2018-05-02 03:45:10,319: radical.entk.wfprocessor.0001: wfprocessor                     : enqueue-thread : INFO    : Enqueue thread terminated
2018-05-02 03:45:10,320: radical.entk.wfprocessor.0001: wfprocessor                     : enqueue-thread : ERROR   : Error in enqueue-thread:
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 379, in _enqueue
    self._mq_connection.close()
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 688, in close
    self._flush_output(self._closed_result.is_ready)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 440, in _flush_output
    raise exceptions.ConnectionClosed()
ConnectionClosed

Exception in thread enqueue-thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 397, in _enqueue
    raise Error(text=ex)
Error: Error:

2018-05-02 03:45:10,322: radical.entk.wfprocessor.0001: wfprocessor                     : MainThread     : INFO    : Terminating dequeue-thread
2018-05-02 03:45:10,323: radical.entk.wfprocessor.0001: wfprocessor                     : dequeue-thread : INFO    : Terminated dequeue thread
2018-05-02 03:45:10,443: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating synchronizer thread
2018-05-02 03:45:10,443: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Synchronizer thread terminated
Traceback (most recent call last):
  File "run.py", line 98, in <module>
    Exchange_gen            = synchronousExchange.GeneralCycle(Replicas, Replica_Cores, Cycle, MD_Executable, ExchangeMethod)
  File "/home/scm177/RepEx3.0/src/radical/repex/SyncEx.py", line 263, in GeneralCycle
    md_tsk.link_input_data = ['%s/restrt > inpcrd'%(self.Book[Cycle-1][ExchangeArray[r]]),
IndexError: list index out of range

```
Logs are [here](https://github.com/radical-cybertools/saga-python/files/1965747/job-disappeared.tar.gz)

**Comment by andre-merzky** [comment]
SAGA  is actually doing something sensible here - it lost track of the pilot job, interprets that as the job being `DONE`, and informs the upper layers (RP / EnTK) about the pilot's completion.  I'm afraid the reaction on that is what trips the application, thus pinging @vivek-bala .

**Comment by SrinivasMushnoori** [comment]
I did some more digging into the logs and the way the above error is phrased, i.e. `backend` and losing track of jobs etc., and suspected that clearing my mongodb might help. Turns out, it did. 
The jobs run to completion now. However, this feels more like a shot in the dark that somehow landed a hit. I'd like to understand WHY clearing the mongodb worked. Comments?

**Comment by andre-merzky** [comment]
that indeed looks like a shot in the dark, and I am in fact surprised that this helped.  A MongoDB cleanup can be needed if some DB limit are reached (size, number of collections, etc) - but that usually gets triggered already on the client side, and has nothing to do with the SAGA layer, nor should it affect pilot runtime (at least not repeatedly)...  Hmmm...

**Comment by andre-merzky** [comment]
Srinivas, the logfiles you attached originally *do* show a MongoDB error  (in the agent), but do *not* show the SAGA error you mentioned initially.  Could it be that two different failure modes applied to different   runs?

**Comment by lee212** [comment]
it is entk related.
