### ISSUE TITLE
Heterogeneous cluster from SAGA when submitting a job to Comet

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/saga-python#676]
When we try to submit a job to Comet with RP we see the following error:
```
2018-05-30 15:00:07,203: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/aymen/.local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 488, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/aymen/.local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 673, in _start_pilot_bulk
    js = rs.job.Service(js_ep, session=self._session)
  File "/home/aymen/.local/lib/python2.7/site-packages/saga/job/service.py", line 115, in __init__
    url, session, ttype=_ttype)
  File "/home/aymen/.local/lib/python2.7/site-packages/saga/base.py", line 104, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/home/aymen/.local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/aymen/.local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 293, in init_instance
    self._open()
  File "/home/aymen/.local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 388, in _open
    assert(len(ppn_vals) == 1), 'heterogeneous cluster'
AssertionError: heterogeneous cluster
2018-05-30 15:00:07,206: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
```
We use SAGA v0.47.5.

**Comment by andre-merzky** [comment]
This seems already fixed in saga devel - can you give it a try, please?

```
#!/usr/bin/env python

import saga

if __name__ == "__main__":

    js = saga.job.Service("slurm+gsissh://comet.sdsc.xsede.org/")
    jd = saga.job.Description()

    jd.executable        = '/bin/date'
    jd.wall_time_limit   = 1
    jd.queue             = "debug"
    jd.project           = "TG-MCB090174"

    job = js.create_job(jd)
    print "Job ID    : %s" % (job.id)
    print "Job State : %s" % (job.state)

    job.run()
    print "Job State : %s" % (job.state)

    job.wait()
    print "Job State : %s" % (job.state)
    print "Exitcode  : %s" % (job.exit_code)

    js.close()
```

**Comment by AymenFJA** [comment]
Hello Andre, I gave it a try and I got this 

Job ID    : None
Job State : New
Job State : Pending
Job State : Done
Exitcode  : 0

**Comment by andre-merzky** [comment]
That is indeed what you should see - great!  This fix will make it into the next release, which is due the next couple of days.

**Comment by AymenFJA** [comment]
Hi @andre-merzky 
So,  I did run the code above again  trying to see what happened and I got the error below :
```
File "andre_test.py", line 7, in <module>
js = saga.job.Service("slurm+gsissh://comet.sdsc.xsede.org/")
File "/home/aymen/devel/local/lib/python2.7/site-packages/saga/job/service.py", line 115, in __init__
url, session, ttype=_ttype)
File "/home/aymen/devel/local/lib/python2.7/site-packages/saga/base.py", line 104, in __init__
self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
File "/home/aymen/devel/local/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
return sync_function (self, *args, **kwargs)
File "/home/aymen/devel/local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 293, in init_instance
self._open()
File "/home/aymen/devel/local/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py", line 388, in _open
assert(len(ppn_vals) == 1), 'heterogeneous cluster'
AssertionError: heterogeneous cluster
```
My radical stack is :

```
python               : 2.7.12
pythonpath           :
virtualenv           : /home/aymen/devel

radical.entk         : 0.6.3
radical.pilot        : 0.47.14-v0.47.14-177-g1061be2@devel
radical.utils        : 0.47.5-v0.47.5-24-gbfeb8d4@devel
saga                 : 0.47.6-v0.47.6-34-gc6b4844@devel
```

**Comment by andre-merzky** [comment]
Aymen, can you please try the SAGA branch `fix/issue_676`?  Thanks!

**Comment by AymenFJA** [comment]
Thanks Andre, I will do ASAP and will let you know.

**Comment by andre-merzky** [comment]
this is merged now and considered fixed.
