### ISSUE TITLE
File copy failed with mput

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/saga-python#677]
This error comes up when I try to run an RP script with Bridges as the target:

```
2018-05-31 15:20:00,441: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 489, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 656, in _start_pilot_bulk
    js_tmp  = rs.job.Service(js_url, session=self._session)
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/job/service.py", line 115, in __init__
    url, session, ttype=_ttype)
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/base.py", line 104, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py", line 516, in init_instance
    self.initialize ()
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py", line 589, in initialize
    self.shell.write_to_remote (src, tgt)
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 836, in write_to_remote
    raise ptye.translate_exception (e)
DoesNotExist: file copy failed: mput None "/tmp/rs_pty_staging_dPpSI0.tmp" ".saga/adaptors/shell_job//wrapper.sh"
stat None: No such file or directory
sftp>  (/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/utils/pty_shell.py +1016 (run_copy_to)  :  raise se.DoesNotExist._log (info['logger'], "file copy failed: %s" % str(out)))
2018-05-31 15:20:00,441: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
```
My stack is:

```
  python               : 2.7.15
  pythonpath           :
  virtualenv           : rpdevel

  radical.pilot        : 0.47.12-v0.47.12-167-ge60920e@devel
  radical.utils        : 0.47.4-merge-pre_gpu-20-gb444067@devel
  saga                 : 0.47.4-v0.47.4-31-gdf6deb4@devel
```

Running any example with Bridges as the target should be enough to reproduce this error

**Comment by iparask** [comment]
Hello Andre,

I tried to run again on Bridges. I do not see the above error, but now I am getting:
```
2018-06-04 08:48:34,474: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : DEBUG   : jd: {'Arguments': ['-l /home/paraskev/radical.pilot.sandbox/rp.session.js-157-203.jetstream-cloud.org.iparask.017686.0002/bootstrap_0.sh',
               " -d 'radical.utils-0.47.4-merge-pre-gpu-22-ga942c4b-devel.tar.gz:saga-python-0.47.4-v0.47.4-32-g71a9765-devel.tar.gz:radical.pilot-0.47.12-v0.47.12-167-ge60920e-devel.tar.gz' -p 'pilot.0000' -s 'rp.session.js-157-203.jetstream-cloud.org.iparask.017686.0002' -m 'create' -r 'local' -b 'default' -g 'default' -v '/home/paraskev/radical.pilot.sandbox/ve.xsede.bridges.0.47.12' -y '15' -e 'module purge' -e 'module load gcc' -e 'module load mpi/gcc_openmpi' -e 'module load slurm' -e 'module load python2'"],
 'CandidateHosts': None,
 'Environment': {},
 'Error': 'bootstrap_1.err',
 'Executable': '/bin/bash',
 'FileTransfer': [],
 'Name': 'pilot.0000',
 'Output': 'bootstrap_1.out',
 'ProcessesPerHost': 0,
 'Project': 'TG-MCB090174',
 'Queue': 'RM',
 'SPMDVariation': None,
 'TotalCPUCount': 64,
 'TotalGPUCount': 0,
 'TotalPhysicalMemory': None,
 'WallTimeLimit': 15,
 'WorkingDirectory': '/home/paraskev/radical.pilot.sandbox/rp.session.js-157-203.jetstream-cloud.org.iparask.017686.0002/pilot.0000/'}
2018-06-04 08:48:36,001: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 489, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 690, in _start_pilot_bulk
    jc.run()
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/task.py", line 405, in run
    % (future.exception))
NoSuccess: future exception: Couldn't get job id from submitted job! sbatch output:
sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified
removed ‘tmp_4rB8CV.slurm’
 (/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py +546 (_job_run)  :  " sbatch output:\n%s" % out)) (/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/task.py +405 (run)  :  % (future.exception)))
2018-06-04 08:48:36,001: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
```

**Comment by andre-merzky** [comment]
Sounds like you cannot submit to queue `RM` under `TG-MCB090174` ?  Can you please check if that combination is supposed to work?

**Comment by iparask** [comment]
This is solved.
