### ISSUE TITLE
SAGA does not submit correctly to Bridges GPU queue

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/saga-python#679]
I created the following pilot-description:
```
        pdesc.resource = 'xsede.bridges'
        pdesc.access_schema = 'gsissh'
        pdesc.project = ... #Has the correct value
        pdesc.gpus = 1
        pdesc.cores = 1
        pdesc.runtime = 20
        pdesc.exit_on_error = True
        pdesc.queue = 'GPU-small'
```

And when SAGA tried to submit it reported the following:
```
Traceback (most recent call last):
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 489, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 690, in _start_pilot_bulk
    jc.run()
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/task.py", line 405, in run
    % (future.exception))
NoSuccess: future exception: Couldn't get job id from submitted job! sbatch output:
sbatch: unrecognized option '--gpus=1'
sbatch: error: No gpu count given, specify --gres=gpu
             See https://www.psc.edu/bridges/user-guide/running-jobs
sbatch: error: Batch job submission failed: Invalid generic resource (gres) specification
removed ‘tmp_pFwdfj.slurm’
```

My stack is:
```
  python               : 2.7.15
  pythonpath           :
  virtualenv           : rpdevel

  radical.pilot        : 0.47.12-v0.47.12-167-ge60920e@devel
  radical.utils        : 0.47.4-merge-pre_gpu-22-ga942c4b@devel
  saga                 : 0.47.4-v0.47.4-32-g71a9765@devel
```

**Comment by andre-merzky** [comment]
Thanks @iparask - can you please try the `fix/issue_679` branch?

**Comment by iparask** [comment]
I get the same error:
```
2018-06-05 10:39:19,311: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 489, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 690, in _start_pilot_bulk
    jc.run()
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/task.py", line 405, in run
    % (future.exception))
NoSuccess: future exception: Couldn't get job id from submitted job! sbatch output:
sbatch: error: Gres format wrong, specify --gres=gpu:TYPE:NUM
             See https://www.psc.edu/bridges/user-guide/running-jobs
sbatch: error: Batch job submission failed: Invalid generic resource (gres) specification
removed ‘tmp_RbCIQN.slurm’
 (/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py +550 (_job_run)  :  " sbatch output:\n%s" % out)) (/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/task.py +405 (run)  :  % (future.exception)))
2018-06-05 10:39:19,312: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
```

**Comment by iparask** [comment]
Apparently it is queue independent:
```
2018-06-05 11:07:58,430: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : DEBUG   : jd: {'Arguments': ['-l /home/paraskev/radical.pilot.sandbox/rp.session.js-157-203.jetstream-clou
d.org.iparask.017687.0002/bootstrap_0.sh',
               " -d 'radical.utils-0.47.4-merge-pre-gpu-22-ga942c4b-devel.tar.gz:saga-python-0.47.4-v0.47.4-33-gdecac07-fix-issue-679.tar.gz:radical.pilot-0.47.12-v0.47.12-167-ge60920e-devel.tar.gz' -p 'pilot.00
00' -s 'rp.session.js-157-203.jetstream-cloud.org.iparask.017687.0002' -m 'create' -r 'local' -b 'default' -g 'default' -v '/home/paraskev/radical.pilot.sandbox/ve.xsede.bridges.0.47.12' -y '20' -e 'module purge
' -e 'module load gcc' -e 'module load mpi/gcc_openmpi' -e 'module load slurm' -e 'module load python2'"],
 'CandidateHosts': None,
 'Environment': {},
 'Error': 'bootstrap_1.err',
 'Executable': '/bin/bash',
 'FileTransfer': [],
 'Name': 'pilot.0000',
 'Output': 'bootstrap_1.out',
 'ProcessesPerHost': 0,
 'Project': 'mc3bggp',
 'Queue': 'GPU',
 'SPMDVariation': None,
 'TotalCPUCount': 1,
 'TotalGPUCount': 4,
 'TotalPhysicalMemory': None,
 'WallTimeLimit': 20,
 'WorkingDirectory': '/home/paraskev/radical.pilot.sandbox/rp.session.js-157-203.jetstream-cloud.org.iparask.017687.0002/pilot.0000/'}
2018-06-05 11:08:00,276: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 489, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 690, in _start_pilot_bulk
    jc.run()
  File "/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/task.py", line 405, in run
    % (future.exception))
NoSuccess: future exception: Couldn't get job id from submitted job! sbatch output:
sbatch: error: Gres format wrong, specify --gres=gpu:TYPE:NUM
             See https://www.psc.edu/bridges/user-guide/running-jobs
sbatch: error: Batch job submission failed: Invalid generic resource (gres) specification
removed ‘tmp_oH7Sz_.slurm’
 (/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-packages/saga/adaptors/slurm/slurm_job.py +550 (_job_run)  :  " sbatch output:\n%s" % out)) (/home/iparask/miniconda2/envs/rpdevel/lib/python2.7/site-pa
ckages/saga/task.py +405 (run)  :  % (future.exception)))
2018-06-05 11:08:00,276: pmgr.0000.launching.0.child: pmgr.0000.launching.0           : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
```

**Comment by andre-merzky** [comment]
Can you please enable PTY level logging, and check what `gres` phrase is created?  Valid phrases are defined [here](https://slurm.schedmd.com/gres.html) - you should get something like `--gres=gpu:1`.

**Comment by iparask** [comment]
Hello Andre,

I just saw that. I tried to take an interactive GPU on Bridges that way:
```
[paraskev@br006 ~]$ interact -h

Usage:  interact [OPTIONS]
  -A Account/ChargeID   ChargeID if not your default"
  --egress              Enable outbound access to external networks
  --gpu                 Allocate 1 gpu in the GPU-shared partition
  --gres=<list>         Specifies a comma delimited list of generic consumable
                    resources. e.g.:    --gres=gpu:1
  --mem=<MB>            Real memory required per node in MegaBytes
  -N Nodes              Number of nodes
  -n NTasks             Number of tasks (spread over all Nodes)
  --ntasks-per-node=<ntasks>    Number of tasks, 1 per core per node.
  -p Partition          Partition/queue you would like to run on
  -R Reservation        Reservation you would like to run on
  -t Time           Set a limit on the total run time. Format include
                        mins, mins:secs, hours:mins:secs.  e.g. 1:30:00

[paraskev@br006 ~]$ interact --gres=gpu:1

A command prompt will appear when your session begins
"Ctrl+d" or "exit" will end your session

srun: error: Unable to allocate resources: Requested node configuration is not available
[paraskev@br006 ~]$ interact -p GPU-small --gres=gpu:1

A command prompt will appear when your session begins
"Ctrl+d" or "exit" will end your session

srun: error: Gres format wrong, specify --gres=gpu:TYPE:NUM
             See https://www.psc.edu/bridges/user-guide/running-jobs
srun: error: Unable to allocate resources: Invalid generic resource (gres) specification
```
When I do `interact -p GPU-small --gres=gpu:p100:1` everything is fine:
```
[paraskev@br006 ~]$ interact -p GPU-small --gres=gpu:p100:1

A command prompt will appear when your session begins
"Ctrl+d" or "exit" will end your session

srun: job 3087381 queued and waiting for resources
^Csrun: Job allocation 3087381 has been revoked
srun: Force Terminated job 3087381
[paraskev@br006 ~]$
```

Bridges has 2 types of GPUs. I think Comet as well. So, it may be necessary to provide the type of requested gpu.

**Comment by iparask** [comment]
Latest debug from SAGA PTY:
```
(rpdevel) iparask@js-157-203:/tmp$ grep gres saga.log
#SBATCH --gres=gpu:4
2018-06-05 20:29:43,801: radical.saga.pty    : pmgr.0000.launching.0           : Thread-2       : DEBUG   : read : [  158] [  225] (sbatch: error: Gres format wrong, specify --gres=gpu:TYPE:NUM \n             See https://www.psc.edu/bridges/user-guide/running-jobs\nsbatch: error: Batch job submission failed: Invalid generic resource (gres) specification\n)
sbatch: error: Gres format wrong, specify --gres=gpu:TYPE:NUM
sbatch: error: Batch job submission failed: Invalid generic resource (gres) specification
(rpdevel) iparask@js-157-203:/tmp$ grep SBATCH saga.log
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --workdir /home/paraskev/radical.pilot.sandbox/rp.session.js-157-203.jetstream-cloud.org.iparask.017688.0000/pilot.0000/
#SBATCH --output bootstrap_1.out
#SBATCH --error bootstrap_1.err
#SBATCH --partition GPU
#SBATCH -J "pilot.0000"
#SBATCH --account 
#SBATCH --time 00:20:00
#SBATCH --gres=gpu:4
#SBATCH -C EGRESS
```

**Comment by andre-merzky** [comment]
*sigh* - so, this is clearly not in sync with documentation, so if you don't mind, please do open a support ticket.  I'll hardcode the gpu type for now, until we get a response.  Is `P100` ok, or do you actually need to be able to set this at runtime?

**Comment by iparask** [comment]
I would say no. Actually let me see how RP's agent discovers GPUs. If the value it gets from the environment is type independent, I will try to give the GPU type at the description.

**Comment by iparask** [comment]
With the hard coding it worked. I suggest to leave this ticket open until we find a more general solution.

**Comment by andre-merzky** [comment]
The RP branch `fix/isue_rs_679` introduces an (indirect) config option - can you give that a try, please?  You'll also need to update RS.

**Comment by iparask** [comment]
The fix is doing `slurm_script += "#SBATCH --gres=gpu:%s:%s\n" % (gpu_arch, total_gpu_count)` which apparently is wrong. it should be
```
slurm_script += "#SBATCH --gres=gpu:%s:%s\n" % (gpu_arch, node_gpu_count)
```
or something similar. I am hardcoding it to run some experiments, until I come up with a fix

**Comment by andre-merzky** [comment]
Is this ticket still  active?

**Comment by andre-merzky** [comment]
This is merged now.
