### ISSUE TITLE
ImportError: No module named colorama

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/saga-python#694]
Again, appears to be originating in SAGA. `bootstrap_0.out` contains the following: 

```
verify module viability: saga            ...Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/02876/srini216/stampede2/radical.pilot.sandbox/re.session.mcewan.engr.rutgers.edu.scm177.017854.0008/pilot.0000/rp_install/lib/python2.7/site-packages/saga/_\
_init__.py", line 8, in <module>
    import radical.utils        as ru
  File "/work/02876/srini216/stampede2/radical.pilot.sandbox/re.session.mcewan.engr.rutgers.edu.scm177.017854.0008/pilot.0000/rp_install/lib/python2.7/site-packages/radica\
l/utils/__init__.py", line 11, in <module>
    from .plugin_manager import PluginManager
  File "/work/02876/srini216/stampede2/radical.pilot.sandbox/re.session.mcewan.engr.rutgers.edu.scm177.017854.0008/pilot.0000/rp_install/lib/python2.7/site-packages/radica\
l/utils/plugin_manager.py", line 14, in <module>
    from .logger import Logger
  File "/work/02876/srini216/stampede2/radical.pilot.sandbox/re.session.mcewan.engr.rutgers.edu.scm177.017854.0008/pilot.0000/rp_install/lib/python2.7/site-packages/radica\
l/utils/logger.py", line 40, in <module>
    import colorama
ImportError: No module named colorama
 failed
python installation cannot load module saga - abort

```

There are no agent side logs. `radical-stack` is
```
  python               : 2.7.14
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/Env_RepEx

  radical.analytics    : v0.45.2-104-ge615742@feature-entk-integration
  radical.entk         : 0.7.10-0.7.10@devel
  radical.pilot        : 0.50.19-v0.50.19@master
  radical.utils        : 0.50.1-v0.50.1-2-gfebbcd0@devel
  saga                 : 0.50.0-v0.50.0-4-gfc8d2e0@devel
```

Client side logs are [here](https://github.com/radical-cybertools/saga-python/files/2596179/logs.tar.gz)

**Comment by iparask** [comment]
Can you please provide `bootstrap_0.out`. Also can you delete the VE in the resource you are using and try again?

**Comment by SrinivasMushnoori** [comment]
Sure, [here](https://github.com/radical-cybertools/saga-python/files/2596199/bootstrap_0.out.tar.gz) it is. 

Attempting to retry after deleting the VE.

**Comment by SrinivasMushnoori** [comment]
Upon retrying, here is what I find:
- the slurm scheduler on Stampede 2 reports that the job status is R, i.e. running. 
- The pilot never goes beyond `PMGR_ACTIVE_PENDING` and wall clock time runs out causing the pilot to fail. 
- the `bootstrap_0.out` file reports the following:

```
Reading http://pypi.python.org/simple/
No local packages or download links found for apache-libcloud
Best match: None
Traceback (most recent call last):
  File "/work/02876/srini216/stampede2/radical.pilot.sandbox/ve.xsede.stampede2_ssh.0.50.19/bin/easy_install", line 8, in <module>
    load_entry_point('setuptools==0.6c11', 'console_scripts', 'easy_install')()
  File "/work/02876/srini216/stampede2/radical.pilot.sandbox/ve.xsede.stampede2_ssh.0.50.19/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy\
_install.py", line 1712, in main
  File "/work/02876/srini216/stampede2/radical.pilot.sandbox/ve.xsede.stampede2_ssh.0.50.19/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy\
_install.py", line 1700, in with_ei_usage
  File "/work/02876/srini216/stampede2/radical.pilot.sandbox/ve.xsede.stampede2_ssh.0.50.19/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy\
_install.py", line 1716, in <lambda>
  File "/opt/apps/intel17/python/2.7.13/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/apps/intel17/python/2.7.13/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/apps/intel17/python/2.7.13/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/work/02876/srini216/stampede2/radical.pilot.sandbox/ve.xsede.stampede2_ssh.0.50.19/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy\
_install.py", line 211, in run
  File "/work/02876/srini216/stampede2/radical.pilot.sandbox/ve.xsede.stampede2_ssh.0.50.19/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy\
_install.py", line 434, in easy_install
  File "/work/02876/srini216/stampede2/radical.pilot.sandbox/ve.xsede.stampede2_ssh.0.50.19/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/package_inde\
x.py", line 475, in fetch_distribution
AttributeError: 'NoneType' object has no attribute 'clone'
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
Couldn't install/upgrade apache-libcloud! Lets see how far we get ...

```

...before continuing to try other things (presumably an alternative)

`bootstrap_0.out` is [here](https://github.com/radical-cybertools/saga-python/files/2596248/bootstrap_0.out.tar.gz)

**Comment by iparask** [comment]
If you check a bit lower you will see that it tries to compile `zmq`. Please allow more time.

**Comment by iparask** [comment]
@SrinivasMushnoori is this still an issue?
